### ISSUE TITLE
Support Generic ATTiny1604/ATTiny804/ATTiny1614/ATTiny814 Boards

### ISSUE THREAD

**Issue by brown131** [platformio/platform-atmelavr#179] opened 2019-12-03 04:16 UTC
Surprisingly in the long list of supported Atmel chips, these chips not currently supported.

**Comment by jamesmyatt** [comment] 2019-12-06 15:24
Duplicate of #83

**Comment by valeros** [comment] 2020-05-06 15:17
Closed as duplicate

**Closed by valeros** 2020-05-06 15:17 UTC
Labels: board request
