### ISSUE TITLE
ATtiny core on steroids

### ISSUE THREAD

**Issue by Thijxx** [platformio/platform-atmelavr#48] opened 2017-04-27 19:44 UTC
Feature request, as described here:
https://community.platformio.org/t/radiohead-compiling-fails-for-attiny85/1777

The core used does not support RadioHead, this is the go-to library for using the cheap green 433MHz chips from China so this would be awesome to have!

Best option:
Better cores for the tiny, like [this one](https://github.com/SpenceKonde/ATTinyCore)

Second best option:
Enable digispark-tiny to use Arduino as ISP

Not so great solution:
Change current ATtiny core so RadioHead compiles

Bonus points:
Simple solition for adding my own core, as described here:
https://github.com/SpenceKonde/ATTinyCore/issues/124

**Comment by ivankravets** [comment] 2017-04-28 21:06
Duplicate of https://github.com/platformio/platform-atmelavr/issues/47

**Closed by ivankravets** 2017-04-28 21:06 UTC
